"""Sample data generated by Faker
"""

import sys
from pathlib import Path

import pandas as pd
from faker import Faker

from malta import MaltaProvider

faker = Faker('mt_MT')
faker.add_provider(MaltaProvider)

COLUMNS = ('Name', 'Surname', 'House', 'Street', 'Locality', 'Phone', 'Country')

OUTPUT_FILE = Path(__file__).with_name('sample_data.xlsx')

# Roughly one address in three in Malta is a flat rather than a named house.
FLAT_SHARE = 3


def get_house_name(faker) -> str:
    if faker.random_int(1, FLAT_SHARE) == 1:
        return faker.flat()

    return faker.house_name()


def get_person_details(faker, count) -> list[dict]:
    data = [
        dict(zip(COLUMNS, (
            faker.first_name(),
            faker.last_name(),
            get_house_name(faker),
            faker.street_name(),
            faker.city(),
            faker.phone_number(),
            'Malta',
        )))
        for _ in range(count)
    ]

    return data


def save_to_excel(data, path=OUTPUT_FILE) -> pd.DataFrame:
    df = pd.DataFrame(data, columns=COLUMNS)
    df.to_excel(path, index=False, sheet_name='People')

    return df


def main():
    # Maltese text uses ħ, ġ, ż and ċ, which the Windows default encoding
    # cannot represent when output is redirected to a file or a pipe.
    sys.stdout.reconfigure(encoding='utf-8')  # type: ignore[union-attr]

    people = get_person_details(faker, 10)
    df = save_to_excel(people)

    print(df.head().to_string())
    print(f'\nSaved {len(df)} rows to {OUTPUT_FILE}')


if __name__ == "__main__":
    main()
